from typing import Protocol

from shifu.learning.core.domain.entities import Goal


class GoalsRepository(Protocol):
    def find_by_id(self, goal_id: str) -> Goal | None: ...

    def find_many_by_account_id(self, account_id: str) -> list[Goal]: ...

    def add(self, goal: Goal) -> None: ...

    def add_many(self, goals: list[Goal]) -> None: ...

    def replace(self, goal: Goal) -> None: ...

    def remove(self, goal: Goal) -> None: ...

    def remove_all(self) -> None: ...
