/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ConfirmEmailIndexRouteImport } from './routes/confirm-email/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as GamificationIndexRouteImport } from './routes/gamification/index'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence/index'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as PendingConfirmationIndexRouteImport } from './routes/pending-confirmation/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as IntelligencePlannerPlanningIdIndexRouteImport } from './routes/intelligence/planner/$planningId/index'
import { Route as LearningGoalsGoalIdIndexRouteImport } from './routes/learning/goals/$goalId/index'
import { Route as LearningGoalsNewIndexRouteImport } from './routes/learning/goals/new/index'
import { Route as LearningGoalsGoalIdSkillsSkillIdIndexRouteImport } from './routes/learning/goals/$goalId/skills/$skillId/index'
import { Route as LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteImport } from './routes/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
import { Route as LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRouteImport } from './routes/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId'
import { Route as LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRouteImport } from './routes/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailIndexRoute = ConfirmEmailIndexRouteImport.update({
  id: '/confirm-email/',
  path: '/confirm-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationIndexRoute = GamificationIndexRouteImport.update({
  id: '/gamification/',
  path: '/gamification/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingConfirmationIndexRoute =
  PendingConfirmationIndexRouteImport.update({
    id: '/pending-confirmation/',
    path: '/pending-confirmation/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligencePlannerPlanningIdIndexRoute =
  IntelligencePlannerPlanningIdIndexRouteImport.update({
    id: '/intelligence/planner/$planningId/',
    path: '/intelligence/planner/$planningId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningGoalsGoalIdIndexRoute =
  LearningGoalsGoalIdIndexRouteImport.update({
    id: '/learning/goals/$goalId/',
    path: '/learning/goals/$goalId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningGoalsNewIndexRoute = LearningGoalsNewIndexRouteImport.update({
  id: '/learning/goals/new/',
  path: '/learning/goals/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningGoalsGoalIdSkillsSkillIdIndexRoute =
  LearningGoalsGoalIdSkillsSkillIdIndexRouteImport.update({
    id: '/learning/goals/$goalId/skills/$skillId/',
    path: '/learning/goals/$goalId/skills/$skillId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute =
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteImport.update({
    id: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId',
    path: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute =
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRouteImport.update(
    {
      id: '/activities/$activityId',
      path: '/activities/$activityId',
      getParentRoute: () =>
        LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute,
    } as any,
  )
const LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute =
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRouteImport.update(
    {
      id: '/materials/$materialId',
      path: '/materials/$materialId',
      getParentRoute: () =>
        LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/confirm-email/': typeof ConfirmEmailIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/gamification/': typeof GamificationIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/pending-confirmation/': typeof PendingConfirmationIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/intelligence/planner/$planningId/': typeof IntelligencePlannerPlanningIdIndexRoute
  '/learning/goals/$goalId/': typeof LearningGoalsGoalIdIndexRoute
  '/learning/goals/new/': typeof LearningGoalsNewIndexRoute
  '/learning/goals/$goalId/skills/$skillId/': typeof LearningGoalsGoalIdSkillsSkillIdIndexRoute
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteWithChildren
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/confirm-email': typeof ConfirmEmailIndexRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/gamification': typeof GamificationIndexRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/learning': typeof LearningIndexRoute
  '/login': typeof LoginIndexRoute
  '/pending-confirmation': typeof PendingConfirmationIndexRoute
  '/register': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/intelligence/planner/$planningId': typeof IntelligencePlannerPlanningIdIndexRoute
  '/learning/goals/$goalId': typeof LearningGoalsGoalIdIndexRoute
  '/learning/goals/new': typeof LearningGoalsNewIndexRoute
  '/learning/goals/$goalId/skills/$skillId': typeof LearningGoalsGoalIdSkillsSkillIdIndexRoute
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteWithChildren
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/confirm-email/': typeof ConfirmEmailIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/gamification/': typeof GamificationIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/pending-confirmation/': typeof PendingConfirmationIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/intelligence/planner/$planningId/': typeof IntelligencePlannerPlanningIdIndexRoute
  '/learning/goals/$goalId/': typeof LearningGoalsGoalIdIndexRoute
  '/learning/goals/new/': typeof LearningGoalsNewIndexRoute
  '/learning/goals/$goalId/skills/$skillId/': typeof LearningGoalsGoalIdSkillsSkillIdIndexRoute
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteWithChildren
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute
  '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId': typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/'
    | '/confirm-email/'
    | '/curriculum/'
    | '/gamification/'
    | '/intelligence/'
    | '/learning/'
    | '/login/'
    | '/pending-confirmation/'
    | '/register/'
    | '/api/auth/$'
    | '/intelligence/planner/$planningId/'
    | '/learning/goals/$goalId/'
    | '/learning/goals/new/'
    | '/learning/goals/$goalId/skills/$skillId/'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/confirm-email'
    | '/curriculum'
    | '/gamification'
    | '/intelligence'
    | '/learning'
    | '/login'
    | '/pending-confirmation'
    | '/register'
    | '/api/auth/$'
    | '/intelligence/planner/$planningId'
    | '/learning/goals/$goalId'
    | '/learning/goals/new'
    | '/learning/goals/$goalId/skills/$skillId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/confirm-email/'
    | '/curriculum/'
    | '/gamification/'
    | '/intelligence/'
    | '/learning/'
    | '/login/'
    | '/pending-confirmation/'
    | '/register/'
    | '/api/auth/$'
    | '/intelligence/planner/$planningId/'
    | '/learning/goals/$goalId/'
    | '/learning/goals/new/'
    | '/learning/goals/$goalId/skills/$skillId/'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId'
    | '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ConfirmEmailIndexRoute: typeof ConfirmEmailIndexRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  GamificationIndexRoute: typeof GamificationIndexRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PendingConfirmationIndexRoute: typeof PendingConfirmationIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  IntelligencePlannerPlanningIdIndexRoute: typeof IntelligencePlannerPlanningIdIndexRoute
  LearningGoalsGoalIdIndexRoute: typeof LearningGoalsGoalIdIndexRoute
  LearningGoalsNewIndexRoute: typeof LearningGoalsNewIndexRoute
  LearningGoalsGoalIdSkillsSkillIdIndexRoute: typeof LearningGoalsGoalIdSkillsSkillIdIndexRoute
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email/': {
      id: '/confirm-email/'
      path: '/confirm-email'
      fullPath: '/confirm-email/'
      preLoaderRoute: typeof ConfirmEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification/': {
      id: '/gamification/'
      path: '/gamification'
      fullPath: '/gamification/'
      preLoaderRoute: typeof GamificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-confirmation/': {
      id: '/pending-confirmation/'
      path: '/pending-confirmation'
      fullPath: '/pending-confirmation/'
      preLoaderRoute: typeof PendingConfirmationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/planner/$planningId/': {
      id: '/intelligence/planner/$planningId/'
      path: '/intelligence/planner/$planningId'
      fullPath: '/intelligence/planner/$planningId/'
      preLoaderRoute: typeof IntelligencePlannerPlanningIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/$goalId/': {
      id: '/learning/goals/$goalId/'
      path: '/learning/goals/$goalId'
      fullPath: '/learning/goals/$goalId/'
      preLoaderRoute: typeof LearningGoalsGoalIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/new/': {
      id: '/learning/goals/new/'
      path: '/learning/goals/new'
      fullPath: '/learning/goals/new/'
      preLoaderRoute: typeof LearningGoalsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/$goalId/skills/$skillId/': {
      id: '/learning/goals/$goalId/skills/$skillId/'
      path: '/learning/goals/$goalId/skills/$skillId'
      fullPath: '/learning/goals/$goalId/skills/$skillId/'
      preLoaderRoute: typeof LearningGoalsGoalIdSkillsSkillIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId': {
      id: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
      path: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
      fullPath: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId'
      preLoaderRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId': {
      id: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/activities/$activityId'
      preLoaderRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRouteImport
      parentRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute
    }
    '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId': {
      id: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId'
      path: '/materials/$materialId'
      fullPath: '/learning/goals/$goalId/skills/$skillId/competencies/$competencyId/materials/$materialId'
      preLoaderRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRouteImport
      parentRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute
    }
  }
}

interface LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteChildren {
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute: typeof LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute
}

const LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteChildren: LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteChildren =
  {
    LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute:
      LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdActivitiesActivityIdRoute,
    LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute:
      LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdMaterialsMaterialIdRoute,
  }

const LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteWithChildren =
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute._addFileChildren(
    LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  ConfirmEmailIndexRoute: ConfirmEmailIndexRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  GamificationIndexRoute: GamificationIndexRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PendingConfirmationIndexRoute: PendingConfirmationIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  IntelligencePlannerPlanningIdIndexRoute:
    IntelligencePlannerPlanningIdIndexRoute,
  LearningGoalsGoalIdIndexRoute: LearningGoalsGoalIdIndexRoute,
  LearningGoalsNewIndexRoute: LearningGoalsNewIndexRoute,
  LearningGoalsGoalIdSkillsSkillIdIndexRoute:
    LearningGoalsGoalIdSkillsSkillIdIndexRoute,
  LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRoute:
    LearningGoalsGoalIdSkillsSkillIdCompetenciesCompetencyIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
