/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as GamificationIndexRouteImport } from './routes/gamification/index'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence/index'
import { Route as LearningIndexRouteImport } from './routes/learning/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as IntelligencePlannerPlanningIdIndexRouteImport } from './routes/intelligence/planner/$planningId/index'
import { Route as LearningGoalsGoalIdIndexRouteImport } from './routes/learning/goals/$goalId/index'
import { Route as LearningGoalsNewIndexRouteImport } from './routes/learning/goals/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationIndexRoute = GamificationIndexRouteImport.update({
  id: '/gamification/',
  path: '/gamification/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligencePlannerPlanningIdIndexRoute =
  IntelligencePlannerPlanningIdIndexRouteImport.update({
    id: '/intelligence/planner/$planningId/',
    path: '/intelligence/planner/$planningId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningGoalsGoalIdIndexRoute =
  LearningGoalsGoalIdIndexRouteImport.update({
    id: '/learning/goals/$goalId/',
    path: '/learning/goals/$goalId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearningGoalsNewIndexRoute = LearningGoalsNewIndexRouteImport.update({
  id: '/learning/goals/new/',
  path: '/learning/goals/new/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/gamification/': typeof GamificationIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/intelligence/planner/$planningId/': typeof IntelligencePlannerPlanningIdIndexRoute
  '/learning/goals/$goalId/': typeof LearningGoalsGoalIdIndexRoute
  '/learning/goals/new/': typeof LearningGoalsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/gamification': typeof GamificationIndexRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/learning': typeof LearningIndexRoute
  '/login': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/intelligence/planner/$planningId': typeof IntelligencePlannerPlanningIdIndexRoute
  '/learning/goals/$goalId': typeof LearningGoalsGoalIdIndexRoute
  '/learning/goals/new': typeof LearningGoalsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/gamification/': typeof GamificationIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/learning/': typeof LearningIndexRoute
  '/login/': typeof LoginIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/intelligence/planner/$planningId/': typeof IntelligencePlannerPlanningIdIndexRoute
  '/learning/goals/$goalId/': typeof LearningGoalsGoalIdIndexRoute
  '/learning/goals/new/': typeof LearningGoalsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/'
    | '/curriculum/'
    | '/gamification/'
    | '/intelligence/'
    | '/learning/'
    | '/login/'
    | '/api/auth/$'
    | '/intelligence/planner/$planningId/'
    | '/learning/goals/$goalId/'
    | '/learning/goals/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/curriculum'
    | '/gamification'
    | '/intelligence'
    | '/learning'
    | '/login'
    | '/api/auth/$'
    | '/intelligence/planner/$planningId'
    | '/learning/goals/$goalId'
    | '/learning/goals/new'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/curriculum/'
    | '/gamification/'
    | '/intelligence/'
    | '/learning/'
    | '/login/'
    | '/api/auth/$'
    | '/intelligence/planner/$planningId/'
    | '/learning/goals/$goalId/'
    | '/learning/goals/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  GamificationIndexRoute: typeof GamificationIndexRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  IntelligencePlannerPlanningIdIndexRoute: typeof IntelligencePlannerPlanningIdIndexRoute
  LearningGoalsGoalIdIndexRoute: typeof LearningGoalsGoalIdIndexRoute
  LearningGoalsNewIndexRoute: typeof LearningGoalsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification/': {
      id: '/gamification/'
      path: '/gamification'
      fullPath: '/gamification/'
      preLoaderRoute: typeof GamificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/planner/$planningId/': {
      id: '/intelligence/planner/$planningId/'
      path: '/intelligence/planner/$planningId'
      fullPath: '/intelligence/planner/$planningId/'
      preLoaderRoute: typeof IntelligencePlannerPlanningIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/$goalId/': {
      id: '/learning/goals/$goalId/'
      path: '/learning/goals/$goalId'
      fullPath: '/learning/goals/$goalId/'
      preLoaderRoute: typeof LearningGoalsGoalIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/goals/new/': {
      id: '/learning/goals/new/'
      path: '/learning/goals/new'
      fullPath: '/learning/goals/new/'
      preLoaderRoute: typeof LearningGoalsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  GamificationIndexRoute: GamificationIndexRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  IntelligencePlannerPlanningIdIndexRoute:
    IntelligencePlannerPlanningIdIndexRoute,
  LearningGoalsGoalIdIndexRoute: LearningGoalsGoalIdIndexRoute,
  LearningGoalsNewIndexRoute: LearningGoalsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
