@baseUrl = http://localhost:7777
@accessToken = replace-with-local-test-token

### Objectives home list
GET {{baseUrl}}/learning/goals
Authorization: Bearer {{accessToken}}

### Goal detail
GET {{baseUrl}}/learning/goals/01SHF000000000000000000012
Authorization: Bearer {{accessToken}}

### Private goal absence
GET {{baseUrl}}/learning/goals/01SHF000000000000000000099
Authorization: Bearer {{accessToken}}

### Unauthenticated goal detail
GET {{baseUrl}}/learning/goals/01SHF000000000000000000012
