/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as GamificationIndexRouteImport } from './routes/gamification/index'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence/index'
import { Route as LearningIndexRouteImport } from './routes/learning/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamificationIndexRoute = GamificationIndexRouteImport.update({
  id: '/gamification/',
  path: '/gamification/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningIndexRoute = LearningIndexRouteImport.update({
  id: '/learning/',
  path: '/learning/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/gamification/': typeof GamificationIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/learning/': typeof LearningIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountIndexRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/gamification': typeof GamificationIndexRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/learning': typeof LearningIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/': typeof AccountIndexRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/gamification/': typeof GamificationIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/learning/': typeof LearningIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/'
    | '/curriculum/'
    | '/gamification/'
    | '/intelligence/'
    | '/learning/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/curriculum'
    | '/gamification'
    | '/intelligence'
    | '/learning'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/curriculum/'
    | '/gamification/'
    | '/intelligence/'
    | '/learning/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountIndexRoute: typeof AccountIndexRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  GamificationIndexRoute: typeof GamificationIndexRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  LearningIndexRoute: typeof LearningIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gamification/': {
      id: '/gamification/'
      path: '/gamification'
      fullPath: '/gamification/'
      preLoaderRoute: typeof GamificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/': {
      id: '/learning/'
      path: '/learning'
      fullPath: '/learning/'
      preLoaderRoute: typeof LearningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountIndexRoute: AccountIndexRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  GamificationIndexRoute: GamificationIndexRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  LearningIndexRoute: LearningIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
