"""initial application schema

Revision ID: a25a7142d3ff
Revises:
Create Date: 2026-09-15 21:03:48.308266

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a25a7142d3ff'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'communication_messages',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('account_id', sa.String(length=26), nullable=True),
        sa.Column('type', sa.String(length=64), nullable=False),
        sa.Column('channel', sa.String(length=40), nullable=False),
        sa.Column('recipient_email', sa.String(length=320), nullable=False),
        sa.Column('recipient_name', sa.String(length=160), nullable=True),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('idempotency_key', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('failure_code', sa.String(length=120), nullable=True),
        sa.Column('provider_message_id', sa.String(length=255), nullable=True),
        sa.Column('attempt_count', sa.Integer(), nullable=False),
        sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('idempotency_key'),
    )
    op.create_table(
        'curriculum_skills',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('description', sa.String(length=4000), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    op.create_table(
        'identity_accounts',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('display_name', sa.String(length=160), nullable=False),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('access_version', sa.Integer(), nullable=False),
        sa.Column('time_zone', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deletion_reason', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_table(
        'learning_goals',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('account_id', sa.String(length=26), nullable=False),
        sa.Column('title', sa.String(length=240), nullable=False),
        sa.Column('description', sa.String(length=4000), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'communication_delivery_attempts',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('communication_id', sa.String(length=26), nullable=False),
        sa.Column('attempt_number', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('provider_message_id', sa.String(length=255), nullable=True),
        sa.Column('failure_code', sa.String(length=120), nullable=True),
        sa.ForeignKeyConstraint(
            ['communication_id'], ['communication_messages.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'curriculum_competencies',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('skill_id', sa.String(length=26), nullable=False),
        sa.Column('name', sa.String(length=160), nullable=False),
        sa.Column('description', sa.String(length=4000), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['skill_id'], ['curriculum_skills.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'curriculum_materials',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('skill_id', sa.String(length=26), nullable=False),
        sa.Column('title', sa.String(length=240), nullable=False),
        sa.Column('content', sa.String(length=20000), nullable=False),
        sa.Column('material_type', sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ['skill_id'], ['curriculum_skills.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'curriculum_skill_foundations',
        sa.Column('skill_id', sa.String(length=26), nullable=False),
        sa.Column('foundation_skill_id', sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ['foundation_skill_id'], ['curriculum_skills.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['skill_id'], ['curriculum_skills.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('skill_id', 'foundation_skill_id'),
    )
    op.create_table(
        'identity_account_action_tokens',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('account_id', sa.String(length=26), nullable=False),
        sa.Column('type', sa.String(length=40), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('token_hash', sa.String(length=255), nullable=False),
        sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['account_id'], ['identity_accounts.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token_hash'),
    )
    op.create_table(
        'learning_skill_experiences',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('goal_id', sa.String(length=26), nullable=False),
        sa.Column('skill_id', sa.String(length=26), nullable=False),
        sa.Column('inclusion_reason', sa.String(length=2000), nullable=True),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completion_summary', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['goal_id'], ['learning_goals.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'curriculum_activities',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('competency_id', sa.String(length=26), nullable=False),
        sa.Column('activity_type', sa.String(length=40), nullable=False),
        sa.Column('difficulty', sa.String(length=40), nullable=False),
        sa.Column('title', sa.String(length=240), nullable=False),
        sa.Column('objective', sa.String(length=4000), nullable=False),
        sa.Column('questions', sa.JSON(), nullable=False),
        sa.Column('evaluation_rule', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ['competency_id'], ['curriculum_competencies.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'curriculum_sequences',
        sa.Column('competency_id', sa.String(length=26), nullable=False),
        sa.Column('items', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ['competency_id'], ['curriculum_competencies.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('competency_id'),
    )
    op.create_table(
        'learning_activity_attempts',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('skill_experience_id', sa.String(length=26), nullable=False),
        sa.Column('competency_id', sa.String(length=26), nullable=False),
        sa.Column('activity_id', sa.String(length=26), nullable=False),
        sa.Column('kind', sa.String(length=40), nullable=False),
        sa.Column('answers', sa.JSON(), nullable=False),
        sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['skill_experience_id'],
            ['learning_skill_experiences.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'learning_competency_progresses',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('skill_experience_id', sa.String(length=26), nullable=False),
        sa.Column('competency_id', sa.String(length=26), nullable=False),
        sa.Column('content_released', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('initial_progress', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('current_progress', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('status', sa.String(length=40), nullable=True),
        sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['skill_experience_id'],
            ['learning_skill_experiences.id'],
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'learning_activity_evaluations',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('attempt_id', sa.String(length=26), nullable=False),
        sa.Column('status', sa.String(length=40), nullable=False),
        sa.Column('parts', sa.JSON(), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('failure_code', sa.String(length=120), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('effect_applied_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['attempt_id'], ['learning_activity_attempts.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('attempt_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_activity_evaluations')
    op.drop_table('learning_competency_progresses')
    op.drop_table('learning_activity_attempts')
    op.drop_table('curriculum_sequences')
    op.drop_table('curriculum_activities')
    op.drop_table('learning_skill_experiences')
    op.drop_table('identity_account_action_tokens')
    op.drop_table('curriculum_skill_foundations')
    op.drop_table('curriculum_materials')
    op.drop_table('curriculum_competencies')
    op.drop_table('communication_delivery_attempts')
    op.drop_table('learning_goals')
    op.drop_table('identity_accounts')
    op.drop_table('curriculum_skills')
    op.drop_table('communication_messages')
    # ### end Alembic commands ###
