"""add mentor session management

Revision ID: be8239ca8cfb
Revises: ba1d8c9e2f34
Create Date: 2026-10-08 21:25:09.893533

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'be8239ca8cfb'
down_revision: str | None = 'ba1d8c9e2f34'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'intelligence_mentor_sessions',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('account_id', sa.String(length=26), nullable=False),
        sa.Column('submission_key', sa.String(length=36), nullable=False),
        sa.Column('content_fingerprint', sa.String(length=64), nullable=True),
        sa.Column('title', sa.String(length=120), nullable=True),
        sa.Column('title_search', sa.String(length=120), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            '(deleted_at IS NULL AND title IS NOT NULL AND title_search IS NOT NULL AND created_at IS NOT NULL AND updated_at IS NOT NULL AND last_activity_at IS NOT NULL AND content_fingerprint IS NOT NULL) OR (deleted_at IS NOT NULL AND title IS NULL AND title_search IS NULL AND created_at IS NULL AND updated_at IS NULL AND last_activity_at IS NULL AND content_fingerprint IS NULL)',
            name='ck_mentor_session_active_or_tombstone',
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'account_id', 'submission_key', name='uq_mentor_submission'
        ),
    )
    op.create_index(
        'ix_mentor_account_activity',
        'intelligence_mentor_sessions',
        ['account_id', 'last_activity_at', 'id'],
        unique=False,
    )
    op.create_table(
        'intelligence_mentor_messages',
        sa.Column('id', sa.String(length=26), nullable=False),
        sa.Column('session_id', sa.String(length=26), nullable=False),
        sa.Column('role', sa.String(length=16), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('in_reply_to_message_id', sa.String(length=26), nullable=True),
        sa.CheckConstraint(
            "(role = 'learner' AND in_reply_to_message_id IS NULL) OR (role = 'mentor' AND in_reply_to_message_id IS NOT NULL)",
            name='ck_mentor_message_role_reply',
        ),
        sa.ForeignKeyConstraint(
            ['in_reply_to_message_id'],
            ['intelligence_mentor_messages.id'],
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['session_id'], ['intelligence_mentor_sessions.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'in_reply_to_message_id', name='uq_mentor_response_per_learner_message'
        ),
    )
    op.create_index(
        'ix_mentor_message_history',
        'intelligence_mentor_messages',
        ['session_id', 'created_at', 'id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_mentor_message_history', table_name='intelligence_mentor_messages'
    )
    op.drop_table('intelligence_mentor_messages')
    op.drop_index(
        'ix_mentor_account_activity', table_name='intelligence_mentor_sessions'
    )
    op.drop_table('intelligence_mentor_sessions')
    # ### end Alembic commands ###
