from typing import Protocol

from shifu.curriculum.core.domain.entities import Material


class MaterialsRepository(Protocol):
    def find_by_id(self, material_id: str) -> Material | None: ...

    def find_many_by_ids(self, material_ids: tuple[str, ...]) -> list[Material]: ...

    def find_many_by_skill_id(self, skill_id: str) -> list[Material]: ...

    def add_many(self, materials: list[Material]) -> None: ...

    def remove_all(self) -> None: ...
